spring.jpa.hibernate.ddl-auto = update
spring.datasource.url=jdbc:mysql:chichi_db/chichi?createDatabaseItNotExist=true
spring.datasource.username=root
spring.datasource.password=74869141

#spring.datasource.generateUniqueName=false
#spring.datasource.name=employee_db
#spring.h2.console.enabled=true
#spring.h2.console.webAllowOthers=true


